Minor changes
DavidFM43/landcover-segmentation pull request #11
Opened 2023-04-27 04:43 UTC by DavidFM43

En esta rama hice unos pocos cambios menores que no afectan directamente la funcionalidad del proyecto:
- Saqué los scripts de la carpeta `src` y los puse en la raíz del proyecto, esto lo hice porque en otros proyectos vi que lo tienen así, este cambio afecta ligeramente las rutas. 
- Arregle un pequeño bug que no mostraba los nombres de las clases en las graficas de W&B-
- Agregue los notebooks de pruebas que he utilizado a la carpeta `notebooks`.
- Agregue el archivo `requirements.txt` con las dependencias del proyecto.
- Arregle algunos errores de escritura en el readme.

2023-04-27 17:50 UTC, eguar11011 commented on README.md
>  ### TODO:
Ese TODO pienso que hay que modificarlo. Ya que no se explica porqué estan esos items ahí.

2023-04-27 17:56 UTC, eguar11011 requested changes
Revisar los comentarios para aprobación.

2023-04-27 17:56 UTC, eguar11011 commented on model.py
Agregar esta tarea como completada en el TODO

2023-04-27 17:56 UTC, eguar11011 commented on README.md
>  ### TODO:
Ese TODO pienso que hay que modificarlo. Ya que no se explica porqué estan esos items ahí.

2023-04-28 04:47 UTC, DavidFM43 commented on README.md
>  ### TODO:
Si es verdad, no sé muy bien que hacer con esos TODOs. ¿Que se le ocurre? ó los dejamos ahí por el momento?

2023-04-28 04:48 UTC, DavidFM43 commented on model.py
Listo

2023-04-29 21:35 UTC, eguar11011 commented on README.md
>  ### TODO:
Podemos dejarlos ahí por el momento, para que se fusionen los otros cambios que realizo.

2023-04-29 21:47 UTC, eguar11011 approved these changes
Listo yo todo lo veo bien.

2023-04-29 21:50 UTC, merged